cars/urls.py
from django.urls import path

from .views import (
    DashBoardView,
    ThanksView,
    CarDetailView,
    BuyersDetailView,
    BuyerThanksView,
    MakeAvailableView,
)


app_name = "cars"

urlpatterns = [
    # Rendering URLS
    path("", DashBoardView.as_view(), name="dashboard"),
    path("thanks/", ThanksView.as_view(), name="seller_thank"),
    path("car-detail/", CarDetailView.as_view(), name="car_detail_form"),
    path("buyer-detail/<pk>", BuyersDetailView.as_view(), name="buyer_detail_form"),
    path("buyer-thanks/", BuyerThanksView.as_view(), name="buyer_thank"),
    path("make-available/<pk>", MakeAvailableView.as_view(), name="make_avaialble"),
]

dodgyBrother/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("cars.urls", namespace="cars")),
    path("user/", include("user.urls", namespace="user")),
]

user/urls.py
from django.urls import path

from .views import LoginView, LogoutView


app_name = "user"

urlpatterns = [
    # Rendering URLS
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

templates/buyerform.html
{% extends "./navbar.html" %}
{% block content %}
<div class="container mt-3">
   <h2>Buyer's Detail Form</h2>
   <form method='POST'>
    {% csrf_token %}
      <div class="mb-3 mt-3">
         <label class="required" for="name">Buyer name</label>
         <input type="text" class="form-control" id="email" placeholder="Enter name" name="name" required>
      </div>
      <div class="mb-3">
         <label class="required" for="pwd">Buyer mobile</label>
         <input type="number" class="form-control" id="mobile" placeholder="Enter mobile" name="mobile" required>
      </div>
      {% for message in messages %}
      <div class="alert alert-danger">
            {{ message }}
      </div>
      {% endfor %}
      <button type="submit" class="btn btn-primary">Submit</button>
   </form>
   
</div>
{% endblock %}

templates/buyerthankyou.html
{% extends "./navbar.html" %}
{% block content %}
<div class="jumbotron d-flex align-items-center min-vh-100">
    <div class="container text-center">
      <h1 class="display-4">Thank You</h1>
      <p class="text-success">Iron mike will be in touch. 
      </p>  
      
    </div>
  </div>
{% endblock %}

templates/cardetailform.html
{% extends "./navbar.html" %}
{% block content %}
<div class="container mt-3">
   <h2>Car Detail Form</h2>
   <form method='POST'>
    {% csrf_token %}
      <div class="mb-3 mt-3">
         <label class="required" for="email">Seller name</label>
         <input type="text" class="form-control" id="email" placeholder="Enter name" name="name" required>
      </div>
      <div class="mb-3">
         <label class="required" for="pwd">Seller mobile</label>
         <input type="number" class="form-control" id="mobile" placeholder="Enter mobile" name="mobile" required>
      </div>
      <div class="mb-3">
         <label class="required" for="pwd">Make</label>
         <input type="text" class="form-control" id="mke" placeholder="eg Ford, Holden etc." name="make" required>
      </div>
      <div class="mb-3">
         <label class="required" for="pwd">Model</label>
         <input type="text" class="form-control" id="model" placeholder="eg Falcon, Commodore etc." name="model" required>
      </div>
      <div class="mb-3">
         <label class="required" for="pwd">Year</label>
         <select class="form-select" aria-label="select example" name='year' required>
            <option selected value="">select year</option>
            {% for year in years %}
            <option value={{year}}>{{year}}</option>
            {% endfor %}
         </select>
      </div>
      <div class="mb-3">
         <label class="required" for="pwd">Condition</label>
         <select class="form-select" aria-label="select example" name="condition" required>
            <option selected value="">select Condition</option>
            <option value="poor">Poor</option>
            <option value="fair">Fair</option>
            <option value="good">Good</option>
            <option value="excellent">Excellent</option>
         </select>
      </div>
      <div class="mb-3">
         <label class="required" for="price">Price range</label>
         <input type="range" name="price" id="ageInputId" value="40000" min="1000" max="100000" oninput="ageOutputId.value = ageInputId.value" required>
          $ <output name="ageOutputName" id="ageOutputId">40000</output>
      </div>
      {% for message in messages %}
    
      <div class="alert alert-danger">
            {{ message }}
      </div>

      {% endfor %}
      <button type="submit" class="btn btn-primary">Submit</button>
   </form>
   
</div>
{% endblock %}

templates/index.html
{% extends "./navbar.html" %}
{% load static %}
{% block content %}
<div class="container">
    <button type="button" class="btn btn-primary mt-4" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Filter .
      </button>


    <div class="row">
        <!-- Button trigger modal -->
        {% if cars|length > 0 %}
        {% for car in cars %}
<div class="card mb-3 me-2 mt-3" style="width: 17rem;">
    <img src="{%static 'images/car.jpeg'%}" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">{{car.name}}</h5>
      <p class="card-text">Description: {{car.make}}, {{car.model}}, {{car.condition}}, {{car.year}}</p>
      <p class="card-text">Price: ${{car.asking_price}}</p>
      {% if car.status == 'Sold' %}
      <h5 class="mt-4 text-danger">Sold<h5>
        {% if user.is_authenticated %}
        <form method='POST' action="{% url 'cars:make_avaialble' pk=car.id%}">
          {% csrf_token %}
        <button class="btn btn-info">Make Car Available </button>
        </form>
        {% endif %}
      
      {% else %}
      <a href="{% url 'cars:buyer_detail_form' pk=car.id %}" class="btn btn-primary">Buy </a>
      {% endif %}
    </div>
  </div>
  {% endfor %}
  {% else %}
    <h3>No results found for your filter</h3>
  {% endif %}
</div>
</div>



<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content ">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Filter Options</h5>
          <button type="button" id="btn-close" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <p>Select an option to filter the result by make or year.</p>
            <form >
                <div class="form-check mb-2">
                <select class="form-select" id="selectmake" aria-label="Default select example">
                  <option selected value="">please select make</option>
                  {% for item in make %} 
                  <option value={{item}}>{{item}}</option>
                  {% endfor %}
                </select>
                </div>
                <div class="form-check">
                <select class="form-select" id="selectyear" aria-label="Default select example">
                  <option selected value="">please select year</option>
                  {% for year in years %} 
                  <option value={{year}}>{{year}}</option>
                  {% endfor %}
                </select>
                </div>
                <span onclick="clearFilter()" class="btn btn-primary mt-3">Clear Filter</span >
                <span onclick="getParameters()" class="btn btn-primary mt-3">Submit</span >
            </form>

        </div>
        
      </div>
    </div>
  </div>

<nav aria-label="Page navigation example">
{% if cars.has_other_pages %}
<ul class="pagination justify-content-center">
  {% if cars.has_previous %}
    <li class="page-item" ><span onclick="getvalues({{ cars.previous_page_number }})" class="page-link" >&laquo;</span></li>
  {% else %}
    <li class="page-item disabled"><span class="page-link" aria-hidden="true">&laquo;</span></li>
  {% endif %}
  {% for i in cars.paginator.page_range %}
    {% if cars.number == i %}
      <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
      <li class="page-item"><span class="page-link" onclick="getvalues({{ i }})">{{ i }}</span></li>
    {% endif %}
  {% endfor %}
  {% if cars.has_next %}
    <li class="page-item" ><span onclick="getvalues({{ cars.next_page_number }})"  class="page-link">&raquo;</span></li>
  {% else %}
    <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
  {% endif %}
</ul>
{% endif %} 
</nav>

<script>
  function getvalues(pagenumber) {
    const params = new URLSearchParams(window. location. search)
    var url = window.location.origin
    if (params. has('make') && params. has('year')){
      var new_url = url + '/?year='+params. get('year')+ '&make='+ params. get('make')+'&page='+pagenumber
    }else if (params. has('year')){
      var new_url = url + '/?year='+params. get('year')+'&page='+pagenumber
    }else if(params. has('make')){
      var new_url = url + '/?make='+params. get('make')+'&page='+pagenumber
    }else{
      var new_url = url + '/?page=' + pagenumber
    }
    window.location.href = new_url 
  }

  function getParameters() {
    var make = document.getElementById("selectmake");
    var make_value = make.options[make.selectedIndex].value;
    var year = document.getElementById("selectyear");
    var year_value = year.options[year.selectedIndex].value;
    var url = window.location.origin
    const params = new URLSearchParams(window. location. search)

    if (make_value != '' && year_value != ''){
      var new_url = '/?make=' + make_value + '&year=' + year_value
    }else if(make_value){
      var new_url = '/?make=' + make_value
    }else{
      var new_url = '/?year=' + year_value
    }
    if (params.has('page')){
      window.location.href = url + new_url + '&page=' + params.get('page')
    }else{
      window.location.href = url + new_url 
    }
    document.getElementById("btn-close").click()
  
  }
  function clearFilter(){
    var url = window.location.origin
    const params = new URLSearchParams(window. location. search)
    if (params.has('page')){
      window.location.href = url  + '/?page=' + params.get('page')
    }else{
      window.location.href = url
    }
  }
</script>
{% endblock %} 

templates/login.html
{% extends "./navbar.html" %}
{% block content %}
<div class="container mt-3">
    <h2 class="mb-4">Login form</h2>
    <form method='POST'>
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Login </button>
    </form>
    {% for message in messages %}
    
      <div class="alert alert-danger mt-3">
            {{ message }}
      </div>

      {% endfor %}
  </div>
{% endblock %}

templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Dodge-Brother</title>
<link rel="stylesheet" type="text/css" href="{%static 'css/main.css'%}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

<body>

<div class="topnav">
  <a class="active" href="/">Home</a>
  <a href=""></a>
  <a href="{% url 'cars:car_detail_form' %}">List-car</a>
  <div class="login-container">
    {% if user.is_authenticated %}
      <form action="{% url 'user:logout' %}">
        <button type="submit">Logout</button>
      </form>
    {% else %}
      {% if request.path != '/user/login/'%}
      <form action="{% url 'user:login' %}">
        <button type="submit">Login </button>
      </form>
      {% endif %}
    {% endif %}
  </div>
</div>

<div style="padding-left:16px">
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

templates/thankyou.html
{% extends "./navbar.html" %}
{% block content %}
<div class="jumbotron d-flex align-items-center min-vh-100">
    <div class="container text-center">
      <h1 class="display-4">Thank You</h1>
      <p class="text-success">Form has been submitted successfully. Seller Listing Id : {{ request.session.id }}
      </p>  
    </div>
  </div>
{% endblock %}